name: Enviar reseñas pendientes

# Se ejecuta cada 5 minutos (ajustable)
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  enviarResenas:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar endpoint de reservas
        uses: fjogele/http-request-action@v1
        with:
          url: https://servicios-holisticos-backend.onrender.com/api/reservas/enviar-resenas-pendientes
          method: GET
